<?php

namespace oihana\m2m ;

use Exception;
use RuntimeException;
use Throwable;

use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Psr7\Response;
use GuzzleHttp\RequestOptions;

use oihana\m2m\enums\AuthScheme;
use oihana\m2m\enums\HttpHeader;
use oihana\m2m\enums\HttpMethod;
use oihana\m2m\files\FileMimeType;

use oihana\m2m\exceptions\KeyfileInvalidException;

use oihana\m2m\schema\Keyfile;
use oihana\m2m\schema\TokenRequestField;
use oihana\m2m\schema\TokenRequestValue;
use oihana\m2m\schema\TokenResponseField;
use oihana\m2m\schema\JWTAlgorithm;
use oihana\m2m\schema\JwtClaim;

/**
 * Lightweight, OIDC-compliant M2M (machine-to-machine) client for an
 * API protected by a JWT issued by an OAuth2 identity provider.
 *
 * Wraps the OAuth 2.0 `client_credentials` flow built on the
 * `urn:ietf:params:oauth:client-assertion-type:jwt-bearer` extension
 * (RFC 7521 + RFC 7523) :
 *
 *  1. Reads a keyfile JSON (RSA private key + connection metadata)
 *     generated by the API at service creation or key rotation.
 *  2. Signs a short-lived JWT bearer assertion with that private key.
 *  3. Exchanges the assertion at the identity provider's token
 *     endpoint for an access token.
 *  4. Calls the resource API with `Authorization: Bearer <access_token>`.
 *
 * The keyfile is expected to be auto-sufficient — it carries
 * `issuer`, `apiBaseUrl`, `audience` and `scope` alongside the RSA
 * material. A third-party developer can therefore connect to the
 * API in two lines :
 *
 * ```php
 * use oihana\m2m\M2MApiClient;
 *
 * $client = M2MApiClient::fromKeyfile( '/secrets/m2m-keyfile.json' ) ;
 * $perms  = $client->get( '/permissions' ) ;
 * $row    = $client->post( '/widgets' , [ 'name' => 'Foo' ] ) ;
 * ```
 *
 * Constructor arguments may still be passed to override any
 * field of the keyfile (typical use case : a developer pointing a
 * staging keyfile at a local API for end-to-end testing).
 *
 * Token lifecycle handling :
 *
 * - **Proactive refresh** — the access_token is cached in memory with
 *   its `expires_in` and reused for every call until 60 seconds before
 *   its expiration. No exchange happens for ~59 minutes on a typical
 *   IdP default.
 * - **Reactive retry on 401** — if the resource API still rejects the
 *   Bearer (clock drift, premature revocation, key rotation, IdP
 *   hiccup), the client invalidates its cache, performs ONE fresh
 *   exchange, and replays the request once. If the retry also fails
 *   with 401, a {@see KeyfileInvalidException} is thrown so the
 *   operator can react (re-download a fresh keyfile from the UI,
 *   after a server-side rotate).
 * - **Distinguish 401 from other failures** — only 401 triggers the
 *   refresh-and-retry. Network errors, 5xx, 403 (denied) bubble up
 *   as-is so they're not masked by a useless re-exchange.
 *
 * Identity provider compatibility :
 *
 * The token endpoint path defaults to `/oauth/v2/token` (Zitadel
 * convention) and may be overridden via the `$tokenPath` constructor
 * argument to match other IdPs (for instance Auth0 expects
 * `/oauth/token`, Keycloak `/realms/{realm}/protocol/openid-connect/token`).
 *
 * @package oihana\m2m
 * @author  Marc Alcaraz
 */
class M2MApiClient
{
    /**
     * Builds an M2M client from a decoded keyfile.
     *
     * The keyfile is expected to be auto-sufficient — i.e. to
     * carry the IdP issuer URL ({@see Keyfile::ISSUER}), the API
     * base URL ({@see Keyfile::API_BASE_URL}) and the requested
     * scope ({@see Keyfile::SCOPE}) alongside the RSA material.
     * Any of these three values may be overridden by the matching
     * constructor argument (typical use case : a developer pointing
     * a staging keyfile at a local API for end-to-end testing).
     *
     * @param array<string, mixed> $keyfile    The decoded keyfile JSON. Must carry `key` + `keyId` + one of `userId` / `clientId`.
     * @param string|null          $issuer     Optional override for `keyfile.issuer` — the IdP issuer URL (without trailing slash — rtrimmed if present).
     * @param string|null          $apiBaseUrl Optional override for `keyfile.apiBaseUrl` — the resource API base URL (without trailing slash).
     * @param Client|null          $http       Optional pre-configured Guzzle client. Useful for tests or for injecting middlewares (logging, retry-on-5xx, telemetry).
     * @param string|null          $scope      Optional override for `keyfile.scope` — the OAuth2 scope to request. Falls back to {@see TokenRequestValue::DEFAULT_SCOPE} when neither this argument nor the keyfile carry one.
     * @param string|null          $tokenPath  Optional override for the token endpoint path on the issuer host. Defaults to {@see self::DEFAULT_TOKEN_PATH} (`/oauth/v2/token`, Zitadel convention). Set this to match other IdPs (e.g. `/oauth/token` for Auth0).
     *
     * @throws RuntimeException When the keyfile lacks the required fields, or when `issuer` / `apiBaseUrl` cannot be resolved from either the keyfile or an override.
     */
    public function __construct
    (
        array   $keyfile    ,
        ?string $issuer     = null ,
        ?string $apiBaseUrl = null ,
        ?Client $http       = null ,
        ?string $scope      = null ,
        ?string $tokenPath  = null
    )
    {
        if
        (
               empty( $keyfile[ Keyfile::KEY    ] )
            || empty( $keyfile[ Keyfile::KEY_ID ] )
            || ( empty( $keyfile[ Keyfile::USER_ID ] ) && empty( $keyfile[ Keyfile::CLIENT_ID ] ) )
        )
        {
            throw new RuntimeException
            (
                'Keyfile is malformed — required fields: '
                . Keyfile::KEY    . ', '
                . Keyfile::KEY_ID . ', and one of '
                . Keyfile::USER_ID . ' or ' . Keyfile::CLIENT_ID . '.'
            ) ;
        }

        $resolvedIssuer     = $issuer     ?? ( is_string( $keyfile[ Keyfile::ISSUER       ] ?? null ) ? $keyfile[ Keyfile::ISSUER       ] : null ) ;
        $resolvedApiBaseUrl = $apiBaseUrl ?? ( is_string( $keyfile[ Keyfile::API_BASE_URL ] ?? null ) ? $keyfile[ Keyfile::API_BASE_URL ] : null ) ;

        if( $resolvedIssuer === null || $resolvedIssuer === '' )
        {
            throw new RuntimeException
            (
                'Keyfile is incomplete — `' . Keyfile::ISSUER . '` is missing and no override was provided.'
            ) ;
        }

        if( $resolvedApiBaseUrl === null || $resolvedApiBaseUrl === '' )
        {
            throw new RuntimeException
            (
                'Keyfile is incomplete — `' . Keyfile::API_BASE_URL . '` is missing and no override was provided.'
            ) ;
        }

        $resolvedScope = $scope
            ?? ( is_string( $keyfile[ Keyfile::SCOPE ] ?? null ) ? $keyfile[ Keyfile::SCOPE ] : null )
            ?? TokenRequestValue::DEFAULT_SCOPE ;

        $resolvedTokenPath = $tokenPath ?? self::DEFAULT_TOKEN_PATH ;

        if( strncmp( $resolvedTokenPath , '/' , 1 ) !== 0 )
        {
            $resolvedTokenPath = '/' . $resolvedTokenPath ;
        }

        $this->keyfile    = $keyfile ;
        $this->issuer     = rtrim( $resolvedIssuer     , '/' ) ;
        $this->apiBaseUrl = rtrim( $resolvedApiBaseUrl , '/' ) ;
        $this->scope      = $resolvedScope ;
        $this->tokenPath  = $resolvedTokenPath ;
        $this->http       = $http ?? new Client( [ 'http_errors' => false , 'verify' => true , 'timeout' => 15 ] ) ;
    }

    /**
     * Lifetime of the JWT bearer assertion sent to the token endpoint,
     * in seconds. 60 seconds is more than enough — the assertion is
     * consumed immediately by the IdP and never replayed.
     */
    public const ASSERTION_TTL_SECONDS = 60 ;

    /**
     * Default token endpoint path on the issuer host. Matches the
     * Zitadel convention. Override via the `$tokenPath` constructor
     * argument for IdPs that expose the token endpoint elsewhere
     * (e.g. Auth0 → `/oauth/token`).
     */
    public const DEFAULT_TOKEN_PATH = '/oauth/v2/token' ;

    /**
     * Default access token TTL (seconds) when the token endpoint
     * response does not carry an `expires_in` field.
     */
    public const DEFAULT_TOKEN_TTL = 3600 ;

    /**
     * Refresh the cached token this many seconds before its hard
     * expiration to avoid 401s caused by clock drift between the
     * client and the identity provider.
     */
    public const REFRESH_SAFETY_MARGIN = 60 ;

    /**
     * Resolved base URL of the resource API
     * (e.g. `https://api.example.com`). The trailing slash is
     * stripped at construction so request paths can be
     * concatenated as `$apiBaseUrl . $path` without ambiguity.
     */
    private string $apiBaseUrl ;

    /**
     * Cached access token returned by the IdP at the most recent
     * exchange. Reused for every authenticated call until
     * {@see self::REFRESH_SAFETY_MARGIN} seconds before its hard
     * expiration. Reset to `null` on a 401 retry to force a fresh
     * exchange.
     */
    private ?string $cachedToken = null ;

    /**
     * Unix timestamp (seconds, UTC) at which {@see self::$cachedToken}
     * stops being usable. Computed as `now + expires_in` at
     * exchange time, falling back to {@see self::DEFAULT_TOKEN_TTL}
     * when the token endpoint omits `expires_in`. Reset to `0`
     * together with {@see self::$cachedToken} on a 401 retry.
     */
    private int $cachedExpiresAt = 0 ;

    /**
     * Underlying Guzzle HTTP client. Used both for the token
     * endpoint exchange and for the authenticated calls to the
     * resource API. May be replaced via the constructor for tests
     * or to inject middlewares (logging, retry-on-5xx, telemetry).
     */
    private Client $http ;

    /**
     * Resolved IdP issuer URL (e.g. `https://my-org.zitadel.cloud`).
     * The token endpoint is derived as `$issuer . $tokenPath`.
     * The trailing slash is stripped at construction so the
     * concatenation never produces a double-slash.
     */
    private string $issuer ;

    /**
     * Decoded keyfile JSON. Holds the RSA material
     * ({@see Keyfile::KEY} + {@see Keyfile::KEY_ID}), the client
     * identity ({@see Keyfile::USER_ID} and/or
     * {@see Keyfile::CLIENT_ID}) and any connection metadata not
     * overridden by the constructor ({@see Keyfile::AUDIENCE},
     * {@see Keyfile::SCOPE}, {@see Keyfile::ISSUER},
     * {@see Keyfile::API_BASE_URL}, {@see Keyfile::TYPE}).
     *
     * @var array<string, mixed>
     */
    private array $keyfile ;

    /**
     * Resolved OAuth2 scope requested at the token endpoint
     * (e.g. `openid profile urn:zitadel:iam:org:project:id:<projectId>:aud`).
     * Falls back to {@see TokenRequestValue::DEFAULT_SCOPE} when
     * neither the keyfile nor the constructor provides one.
     */
    private string $scope ;

    /**
     * Resolved token endpoint path on the issuer host (always
     * starting with `/`). Defaults to {@see self::DEFAULT_TOKEN_PATH}.
     */
    private string $tokenPath ;

    /**
     * Issues an authenticated DELETE.
     *
     * @param string $path The request path, relative to
     *                     {@see self::$apiBaseUrl} and starting
     *                     with `/`.
     *
     * @return array<string, mixed> The decoded JSON envelope.
     *
     * @throws KeyfileInvalidException
     * @throws GuzzleException
     */
    public function delete( string $path ) : array
    {
        return $this->call( HttpMethod::DELETE , $path ) ;
    }

    /**
     * Convenience factory : reads the keyfile JSON from the given
     * path and forwards to the constructor.
     *
     * Most callers can omit `$issuer` / `$apiBaseUrl` / `$scope` —
     * the API enriches the keyfile with these fields at service
     * creation so the file is auto-sufficient. Pass them only to
     * override what the keyfile carries (cf. {@see __construct}).
     *
     * @param string      $keyfilePath The absolute path to the keyfile
     *                                  JSON on disk.
     * @param string|null $issuer      Optional override for
     *                                  `keyfile.issuer`.
     * @param string|null $apiBaseUrl  Optional override for
     *                                  `keyfile.apiBaseUrl`.
     * @param Client|null $http        Optional pre-configured Guzzle
     *                                  client.
     * @param string|null $scope       Optional override for
     *                                  `keyfile.scope`.
     * @param string|null $tokenPath   Optional override for the token
     *                                  endpoint path. See {@see __construct}.
     *
     * @return self The freshly constructed M2M client.
     *
     * @throws RuntimeException When the file cannot be read, when
     *                          the contents do not parse as a JSON
     *                          object, or when the keyfile is
     *                          malformed (cf. {@see __construct}).
     */
    public static function fromKeyfile
    (
        string  $keyfilePath ,
        ?string $issuer      = null ,
        ?string $apiBaseUrl  = null ,
        ?Client $http        = null ,
        ?string $scope       = null ,
        ?string $tokenPath   = null
    )
    : self
    {
        $raw = @file_get_contents( $keyfilePath ) ;

        if( $raw === false )
        {
            throw new RuntimeException( "Keyfile not readable: $keyfilePath" ) ;
        }

        $decoded = json_decode( $raw , true ) ;

        if( !is_array( $decoded ) )
        {
            throw new RuntimeException( "Keyfile is not a valid JSON object: $keyfilePath" ) ;
        }

        /** @var array<string, mixed> $decoded */
        return new self( $decoded , $issuer , $apiBaseUrl , $http , $scope , $tokenPath ) ;
    }

    /**
     * Issues an authenticated GET.
     *
     * @param string $path The request path, relative to
     *                     {@see self::$apiBaseUrl} and starting
     *                     with `/`.
     *
     * @return array<string, mixed> The decoded JSON envelope.
     *
     * @throws KeyfileInvalidException
     * @throws GuzzleException
     */
    public function get( string $path ) : array
    {
        return $this->call( HttpMethod::GET , $path ) ;
    }

    /**
     * Returns a valid access_token. Performs a fresh exchange against
     * the identity provider when the cached token is missing or about
     * to expire.
     *
     * The JWT bearer assertion uses {@see Keyfile::USER_ID} as both
     * `iss` and `sub` when present (modern service-account
     * keyfiles), and falls back to {@see Keyfile::CLIENT_ID} for
     * legacy API-app keyfiles. Either is sufficient for an IdP
     * to identify the M2M client.
     *
     * Public to allow consumers (smoke tests, power users) to
     * pre-warm the cache, validate the IdP exchange in isolation
     * from any API call, or feed the raw token to a third-party
     * library.
     *
     * @return string The cached access token, ready to be sent in
     *                an `Authorization: Bearer …` header.
     *
     * @throws KeyfileInvalidException When the IdP refuses the JWT
     *                                  bearer assertion or returns
     *                                  a 200 with an empty body.
     */
    public function getToken() : string
    {
        if( $this->cachedToken !== null && time() < $this->cachedExpiresAt - self::REFRESH_SAFETY_MARGIN )
        {
            return $this->cachedToken ;
        }

        $now     = time() ;
        $userId  = is_string( $this->keyfile[ Keyfile::USER_ID   ] ?? null ) ? $this->keyfile[ Keyfile::USER_ID   ] : null ;
        $cliId   = is_string( $this->keyfile[ Keyfile::CLIENT_ID ] ?? null ) ? $this->keyfile[ Keyfile::CLIENT_ID ] : null ;
        $subject = $userId ?? $cliId ?? '' ;
        $keyId   = is_string( $this->keyfile[ Keyfile::KEY_ID    ] ?? null ) ? $this->keyfile[ Keyfile::KEY_ID    ] : '' ;
        $key     = is_string( $this->keyfile[ Keyfile::KEY       ] ?? null ) ? $this->keyfile[ Keyfile::KEY       ] : '' ;

        $assertion = $this->signAssertion
        (
            [
                JwtClaim::ISSUER     => $subject ,
                JwtClaim::SUBJECT    => $subject ,
                JwtClaim::AUDIENCE   => $this->issuer ,
                JwtClaim::ISSUED_AT  => $now ,
                JwtClaim::EXPIRES_AT => $now + self::ASSERTION_TTL_SECONDS ,
            ] ,
            $key ,
            $keyId
        ) ;

        try
        {
            // RFC 7523 jwt-bearer authorization grant : the JWT
            // itself is the identity proof. Distinct from the
            // `client_credentials` + `client_assertion` pair,
            // which authenticates an OAuth-registered client.
            // Service Users / non-OAuth-registered identities are
            // NOT accepted by the `client_credentials` flow, which
            // would return `invalid_client - client not found`.
            $response = $this->http->post( "$this->issuer$this->tokenPath" ,
            [
                RequestOptions::FORM_PARAMS =>
                [
                    TokenRequestField::GRANT_TYPE => TokenRequestValue::GRANT_JWT_BEARER ,
                    TokenRequestField::SCOPE      => $this->scope ,
                    TokenRequestField::ASSERTION  => $assertion ,
                ] ,
            ]) ;
        }
        catch( Throwable $e )
        {
            throw new KeyfileInvalidException
            (
                'Unable to reach the identity provider token endpoint: ' . $e->getMessage() ,
                0 ,
                $e instanceof Exception ? $e : null
            ) ;
        }

        $status = $response->getStatusCode() ;
        $raw    = (string) $response->getBody() ;

        if( $status !== 200 )
        {
            throw new KeyfileInvalidException
            (
                "Identity provider rejected the JWT bearer assertion (HTTP $status): " . substr( $raw , 0 , 400 )
            ) ;
        }

        $payload = json_decode( $raw , true ) ;

        if
        (
               !is_array( $payload )
            || empty( $payload[ TokenResponseField::ACCESS_TOKEN ] )
            || !is_string( $payload[ TokenResponseField::ACCESS_TOKEN ] )
        )
        {
            throw new KeyfileInvalidException( 'Identity provider returned a 200 with no access_token in the body.' ) ;
        }

        $expiresIn             = $payload[ TokenResponseField::EXPIRES_IN ] ?? self::DEFAULT_TOKEN_TTL ;
        $this->cachedToken     = $payload[ TokenResponseField::ACCESS_TOKEN ] ;
        $this->cachedExpiresAt = $now + ( is_int( $expiresIn ) ? $expiresIn : ( is_numeric( $expiresIn ) ? (int) $expiresIn : self::DEFAULT_TOKEN_TTL ) ) ;

        return $this->cachedToken ;
    }

    /**
     * Issues an authenticated PATCH.
     *
     * @param string               $path The request path, relative
     *                                    to {@see self::$apiBaseUrl}
     *                                    and starting with `/`.
     * @param array<string, mixed> $body The JSON body to send.
     *
     * @return array<string, mixed> The decoded JSON envelope.
     *
     * @throws KeyfileInvalidException
     * @throws GuzzleException
     */
    public function patch( string $path , array $body ) : array
    {
        return $this->call( HttpMethod::PATCH , $path , $body ) ;
    }

    /**
     * Issues an authenticated POST.
     *
     * @param string               $path The request path, relative
     *                                    to {@see self::$apiBaseUrl}
     *                                    and starting with `/`.
     * @param array<string, mixed> $body The JSON body to send.
     *
     * @return array<string, mixed> The decoded JSON envelope.
     *
     * @throws KeyfileInvalidException
     * @throws GuzzleException
     */
    public function post( string $path , array $body ) : array
    {
        return $this->call( HttpMethod::POST , $path , $body ) ;
    }

    /**
     * Issues an authenticated PUT.
     *
     * @param string               $path The request path, relative
     *                                    to {@see self::$apiBaseUrl}
     *                                    and starting with `/`.
     * @param array<string, mixed> $body The JSON body to send.
     *
     * @return array<string, mixed> The decoded JSON envelope.
     *
     * @throws KeyfileInvalidException
     * @throws GuzzleException
     */
    public function put( string $path , array $body ) : array
    {
        return $this->call( HttpMethod::PUT , $path , $body ) ;
    }

    /**
     * Issues an authenticated request, with a one-shot retry on 401.
     *
     * Extension hook : subclasses may override to add per-request
     * instrumentation (timing, correlation ids) or to amend the
     * retry policy without rewriting the public verb methods.
     *
     * @param string                    $method The HTTP method (`GET`, `POST`, …).
     * @param string                    $path   The request path, relative to {@see self::$apiBaseUrl}.
     * @param array<string, mixed>|null $body   The JSON body to send, or `null` for verbs that do not carry one.
     *
     * @return array<string, mixed> The decoded JSON envelope of the API response.
     *
     * @throws KeyfileInvalidException When the keyfile is rejected by the IdP, or when both the cached token
     *                                 AND a fresh one are rejected by the API.
     *
     * @throws GuzzleException On network / non-401 failures.
     */
    protected function call( string $method , string $path , ?array $body = null ) : array
    {
        $response = $this->doRequest( $method , $path , $body , $this->getToken() ) ;

        if( $response->getStatusCode() !== 401 )
        {
            return $this->decodeResponse( $response ) ;
        }

        // 401 — the cached token is stale (or never was valid).
        // Drop it, force a fresh exchange, replay the request once.
        $this->cachedToken     = null ;
        $this->cachedExpiresAt = 0 ;

        $response = $this->doRequest( $method , $path , $body , $this->getToken() ) ;

        if( $response->getStatusCode() === 401 )
        {
            // Two consecutive 401 with distinct fresh tokens means
            // the keyfile itself is no longer accepted (server-side
            // rotation, app deactivation, app deletion).
            throw new KeyfileInvalidException
            (
                'M2M keyfile rejected by the API after a fresh exchange — '
                . 'the application may have been rotated, deactivated or deleted server-side.'
            ) ;
        }

        return $this->decodeResponse( $response ) ;
    }

    /**
     * Decodes a Guzzle response body into an associative array.
     * Returns an empty array when the body is not a JSON object.
     *
     * Extension hook : subclasses may override to support non-JSON
     * payloads or to enforce a typed envelope.
     *
     * @param Response $response The Guzzle response to decode.
     *
     * @return array<string, mixed> The decoded JSON envelope, or
     *                              an empty array when the body
     *                              is not a JSON object.
     */
    protected function decodeResponse( Response $response ) : array
    {
        $raw  = (string) $response->getBody() ;
        $data = json_decode( $raw , true ) ;

        if( !is_array( $data ) )
        {
            return [] ;
        }

        /** @var array<string, mixed> $data */
        return $data ;
    }

    /**
     * Issues a single HTTP request with the provided Bearer.
     *
     * Extension hook : subclasses may override to inject extra
     * headers (correlation ids, tenant headers) without touching
     * the call/retry layer.
     *
     * @param string                    $method The HTTP method
     *                                           (`GET`, `POST`, …).
     * @param string                    $path   The request path,
     *                                           relative to
     *                                           {@see self::$apiBaseUrl}.
     * @param array<string, mixed>|null $body   The JSON body to
     *                                           send, or `null` for
     *                                           verbs that do not
     *                                           carry one.
     * @param string                    $token  The access token to
     *                                           send in the
     *                                           `Authorization`
     *                                           header.
     *
     * @return Response The raw Guzzle response.
     *
     * @throws GuzzleException
     */
    protected function doRequest( string $method , string $path , ?array $body , string $token ) : Response
    {
        $options =
        [
            RequestOptions::HEADERS =>
            [
                HttpHeader::AUTHORIZATION => AuthScheme::prefix( AuthScheme::BEARER ) . $token ,
                HttpHeader::ACCEPT        => FileMimeType::JSON ,
            ] ,
        ] ;

        if( $body !== null )
        {
            $options[ RequestOptions::JSON ] = $body ;
        }

        /** @var Response $response */
        $response = $this->http->request( $method , "$this->apiBaseUrl$path" , $options ) ;

        return $response ;
    }

    /**
     * Builds and signs an RS256 JWT bearer assertion.
     *
     * Inlined here (rather than depending on `firebase/php-jwt`) to keep this PHP 7.4 compatibility branch
     * dependency-light and to avoid pulling in the 6.x line which is flagged by a low-severity,
     * disputed security advisory (CVE-2025-45769) that does not affect the RS256 signing path used here.
     * The 7.x line that fixes the advisory requires PHP 8.0+.
     *
     * @param  array<string, mixed>     $claims The JWT payload claims.
     * @param  string                   $key    The RSA private key in PEM format.
     * @param  string                   $keyId  The `kid` header value.
     * @return string                   The compact JWS (`header.payload.signature`, base64url).
     *
     * @throws KeyfileInvalidException  When the RSA private key cannot be parsed
     *                                  or the OpenSSL signing operation fails.
     */
    private function signAssertion( array $claims , string $key , string $keyId ) : string
    {
        $header =
        [
            'typ' => 'JWT'             ,
            'alg' => JWTAlgorithm::RS256 ,
            'kid' => $keyId            ,
        ] ;

        $headerJson  = json_encode( $header ) ;
        $payloadJson = json_encode( $claims ) ;

        if( $headerJson === false || $payloadJson === false )
        {
            throw new KeyfileInvalidException( 'Unable to JSON-encode the JWT bearer assertion.' ) ;
        }

        $signingInput = self::base64UrlEncode( $headerJson ) . '.' . self::base64UrlEncode( $payloadJson ) ;

        $privateKey = openssl_pkey_get_private( $key ) ;

        if( $privateKey === false )
        {
            throw new KeyfileInvalidException
            (
                'Keyfile RSA private key cannot be parsed by OpenSSL: '
                . ( openssl_error_string() ?: 'unknown error' )
            ) ;
        }

        $signature = '' ;
        $ok        = openssl_sign( $signingInput , $signature , $privateKey , OPENSSL_ALGO_SHA256 ) ;

        if( $ok !== true )
        {
            throw new KeyfileInvalidException
            (
                'OpenSSL failed to sign the JWT bearer assertion: '
                . ( openssl_error_string() ?: 'unknown error' )
            ) ;
        }

        return $signingInput . '.' . self::base64UrlEncode( $signature ) ;
    }

    /**
     * RFC 4648 §5 base64url encoding (URL-safe, no padding).
     *
     * @param  string $raw The raw bytes to encode.
     * @return string      The base64url representation.
     */
    private static function base64UrlEncode( string $raw ) : string
    {
        return rtrim( strtr( base64_encode( $raw ) , '+/' , '-_' ) , '=' ) ;
    }
}
